version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: yatagarasu
      POSTGRES_USER: yatagarasu
      POSTGRES_PASSWORD: yatagarasu
    command: "postgres -c shared_preload_libraries=pg_stat_statements"
    ports:
      - "5432:5432"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  postgres_exporter:
    container_name: postgres_exporter
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://yatagarasu:yatagarasu@host.docker.internal:5432/yatagarasu?sslmode=disable"
    volumes:
      - ./queries.yaml:/queries.yaml
    command:
      - "--extend.query-path=/queries.yaml"
      - "--collector.stat_activity_autovacuum"
      - "--collector.stat_statements"
    ports:
      - "9187:9187"

  process-exporter:
    container_name: process_exporter
    image: ncabatoff/process-exporter
    command:
      - '--procfs=/host/proc'
      - '--config.path=/process-exporter.yml'
    volumes:
      - /proc:/host/proc
      - ./process-exporter.yml:/process-exporter.yml
    ports:
      - '9256:9256'
    privileged: true
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    environment:
      - GF_SECURITY_ADMIN_USER=yatagarasu
      - GF_SECURITY_ADMIN_PASSWORD=yatagarasu
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: always
    ports:
      - '8080:3000'
