Yatagarasu:
  - baseURL: 'http://www.koakjo.com:9290'
  - dbname: 'explorer'
  - nodeExporterJobName: 'node_exporter'
  - postgresExporterJobName: 'postgres_exporter'
Prometheus:
  - nodeExporterDefaultInterval: '15s'
  - postgresExporterDefaultInterval: '15s'