baseURL: 'http://www.koakjo.com:9290'
dbname: 'explorer'
nodeExporterJobName: 'node_exporter'
postgresExporterJobName: 'postgres_exporter'
nodeExporterDefaultInterval: '15s'
postgresExporterDefaultInterval: '15s'