prometheus:
  url: http://localhost:9090
  node_exporter:
    job_name: node_exporter
  process_exporter:
    job_name: process_exporter
  postgres_exporter:
    job_name: postgres_exporter

target_db:
  dbname: yatagarasu

grafana:
  dashboard_urls: [
    https://www.koakjo.com:19300/d/000000039/postgresql-database?orgId=1,
    https://www.koakjo.com:19300/d/rYdddlPWk/node-exporter-full?orgId=1
  ]

status_colors:
  ok: '#00ff00'
  watch: '#ffbf00'
  alert: '#ff0000'
